# Transitions (called "modes"

TRANSITION_ROTATE            = b"a" # Message travels right to left
TRANSITION_HOLD              = b"b" # Message remains stationary
TRANSITION_ROLL_UP           = b"e"
TRANSITION_ROLL_DOWN         = b"f"
TRANSITION_ROLL_LEFT         = b"g"
TRANSITION_ROLL_RIGHT        = b"h"
TRANSITION_WIPE_LEFT         = b"i"
TRANSITION_WIPE_DOWN         = b"j"
TRANSITION_WIPE_LEFT         = b"k"
TRANSITION_WIPE_RIGHT        = b"l"
TRANSITION_SCROLL            = b"m"
TRANSITION_AUTOMODE          = b"o"
TRANSITION_ROLL_IN           = b"p"
TRANSITION_ROLL_OUT          = b"q"
TRANSITION_WIPE_IN           = b"r"
TRANSITION_WIPE_OUT          = b"s"
TRANSITION_COMPRESSED_ROTATE = b"t"
TRANSITION_EXPLODE           = b"u"
TRANSITION_CLOCK             = b"v"

# "Special modes"
TRANSITION_TWINKLE           = b"n0"
TRANSITION_SPARKLE           = b"n1"
TRANSITION_SNOW              = b"n3"
TRANSITION_INTERLOCK         = b"n3"
TRANSITION_SWITCH            = b"n4"
TRANSITION_SLIDE             = b"n5"
TRANSITION_SPRAY             = b"n6"
TRANSITION_STARBURST         = b"n7"
